/**
 * Datos de ejemplo para desarrollar el frontend antes de conectar Supabase.
 *
 * IMPORTANTE: son inventados. No provienen del export `KAME ONE Fichas.xlsx`,
 * que contiene datos personales reales (RUT, teléfono, e-mail) y no debe salir
 * de la carpeta del equipo. Los nombres replican los de los mockups.
 *
 * La cartera real está pendiente de aclaración con el jefe de FPC Servicios:
 * el export trae 434 fichas activas con rol de cliente y él declara 120 activos.
 */

import type { Camion, Cilindro, Cliente, Usuario } from '../dominio/tipos';

export const USUARIOS: Usuario[] = [
  {
    id: 'usr-0001',
    nombre: 'Bastián Núñez',
    usuario: 'bnunez',
    rol: 'tecnico',
    camionAsignadoId: 'cam-0001',
  },
  {
    id: 'usr-0002',
    nombre: 'Nicolás Castillo',
    usuario: 'ncastillo',
    rol: 'admin',
    camionAsignadoId: null,
  },
];

export const CAMIONES: Camion[] = [
  {
    id: 'cam-0001',
    patente: 'JZ-PV-45',
    descripcion: 'Camión de reparto',
    capacidadCilindros: 30,
    activo: true,
  },
  {
    id: 'cam-0002',
    patente: 'KL-RT-12',
    descripcion: 'Camioneta',
    capacidadCilindros: 16,
    activo: true,
  },
];

export const CLIENTES: Cliente[] = [
  {
    id: 'cli-0001',
    rut: '76.123.456-7',
    nombre: 'Industrias Rojas Ltda.',
    direccion: 'Av. Los Industriales 1240, San Bernardo',
    telefono: '+56 2 2345 6789',
    email: 'contacto@industriasrojas.cl',
    region: 'Región Metropolitana',
    rubro: 'Alimentos',
    activo: true,
  },
  {
    id: 'cli-0002',
    rut: '78.987.654-3',
    nombre: 'Constructora San Martín',
    direccion: 'Camino Lo Boza 455, Pudahuel',
    telefono: '+56 2 2871 4400',
    email: null,
    region: 'Región Metropolitana',
    rubro: 'Construcción',
    activo: true,
  },
  {
    id: 'cli-0003',
    rut: '77.456.123-9',
    nombre: 'Metalúrgica Andes',
    direccion: 'Panamericana Sur km 32, Buin',
    telefono: '+56 2 2544 1180',
    email: 'compras@metandes.cl',
    region: 'Región Metropolitana',
    rubro: 'Metalmecánica',
    activo: true,
  },
  {
    id: 'cli-0004',
    rut: '96.543.210-K',
    nombre: 'Clínica Dávila',
    direccion: 'Av. Recoleta 464, Recoleta',
    telefono: '+56 2 2730 8000',
    email: 'abastecimiento@davila.cl',
    region: 'Región Metropolitana',
    rubro: 'Salud',
    activo: true,
  },
  {
    id: 'cli-0005',
    rut: '76.884.221-5',
    nombre: 'Viña Los Robles',
    direccion: 'Ruta I-50 km 12, San Fernando',
    telefono: '+56 72 271 4500',
    email: 'enologia@losrobles.cl',
    region: "Región del Libertador General Bernardo O'Higgins",
    rubro: 'Agroindustria',
    activo: true,
  },
  {
    id: 'cli-0006',
    rut: '77.031.998-2',
    nombre: 'Alimentos del Maule S.A.',
    direccion: 'Camino a Colín 890, Talca',
    telefono: '+56 71 220 3311',
    email: null,
    region: 'Región del Maule',
    rubro: 'Agroindustria',
    activo: true,
  },
];

export const CILINDROS: Cilindro[] = [
  {
    id: 'cil-0001',
    codigo: 'CIL-001234',
    tipoEnvase: 'cilindro',
    tipoGas: 'Oxígeno',
    capacidadValor: 10,
    capacidadUnidad: 'm3',
    estado: 'en_planta',
    clienteActualId: null,
    enClienteDesde: null,
    sinCodigoFabrica: false,
  },
  {
    id: 'cil-0002',
    codigo: 'CIL-001235',
    tipoEnvase: 'cilindro',
    tipoGas: 'Nitrógeno',
    capacidadValor: 10,
    capacidadUnidad: 'm3',
    estado: 'en_planta',
    clienteActualId: null,
    enClienteDesde: null,
    sinCodigoFabrica: false,
  },
  {
    id: 'cil-0003',
    codigo: 'CIL-001236',
    tipoEnvase: 'cilindro',
    tipoGas: 'Argón',
    capacidadValor: 6,
    capacidadUnidad: 'm3',
    estado: 'en_planta',
    clienteActualId: null,
    enClienteDesde: null,
    sinCodigoFabrica: false,
  },
  {
    id: 'cil-0004',
    codigo: 'CIL-001237',
    tipoEnvase: 'cilindro',
    tipoGas: 'CO₂',
    capacidadValor: 25,
    capacidadUnidad: 'kg',
    estado: 'en_cliente',
    clienteActualId: 'cli-0002',
    enClienteDesde: '2026-08-28T10:20:00-04:00',
    sinCodigoFabrica: false,
  },
  {
    id: 'cil-0005',
    codigo: 'CIL-001238',
    tipoEnvase: 'cilindro',
    tipoGas: 'Nitrógeno',
    capacidadValor: 10,
    capacidadUnidad: 'm3',
    estado: 'en_cliente',
    clienteActualId: 'cli-0001',
    enClienteDesde: '2026-09-02T09:45:00-04:00',
    sinCodigoFabrica: false,
  },
  {
    id: 'cil-0006',
    codigo: 'PAQ-000045',
    tipoEnvase: 'paquete',
    tipoGas: 'Nitrógeno',
    capacidadValor: 90,
    capacidadUnidad: 'm3',
    estado: 'en_cliente',
    clienteActualId: 'cli-0005',
    enClienteDesde: '2026-08-14T15:10:00-04:00',
    sinCodigoFabrica: false,
  },
  {
    id: 'cil-0007',
    codigo: 'TER-000012',
    tipoEnvase: 'termo',
    tipoGas: 'Nitrógeno líquido',
    capacidadValor: 195,
    capacidadUnidad: 'kg',
    estado: 'en_cliente',
    clienteActualId: 'cli-0006',
    enClienteDesde: '2026-07-30T11:00:00-04:00',
    sinCodigoFabrica: false,
  },
  {
    // Caso cotidiano: envase sin código de barras de fábrica, dado de alta a mano.
    id: 'cil-0008',
    codigo: 'MAN-000003',
    tipoEnvase: 'cilindro',
    tipoGas: 'Oxígeno',
    capacidadValor: 1,
    capacidadUnidad: 'm3',
    estado: 'en_planta',
    clienteActualId: null,
    enClienteDesde: null,
    sinCodigoFabrica: true,
  },
  {
    id: 'cil-0009',
    codigo: 'CIL-001240',
    tipoEnvase: 'cilindro',
    tipoGas: 'Argón',
    capacidadValor: 6,
    capacidadUnidad: 'm3',
    estado: 'en_cliente',
    clienteActualId: 'cli-0001',
    enClienteDesde: '2026-09-05T13:40:00-04:00',
    sinCodigoFabrica: false,
  },
  {
    id: 'cil-0010',
    codigo: 'CIL-001245',
    tipoEnvase: 'cilindro',
    tipoGas: 'CO₂',
    capacidadValor: 25,
    capacidadUnidad: 'kg',
    estado: 'en_cliente',
    clienteActualId: 'cli-0003',
    enClienteDesde: '2026-09-09T15:20:00-04:00',
    sinCodigoFabrica: false,
  },
];
